### ISSUE TITLE
Add Superpack to "Playing Modpacks"

### ISSUE THREAD

**Issue by Gaming32** [modrinth/docs#105]
### Describe the solution you'd like

Superpack is useful for installing modpacks in the Vanilla launcher. In the future, support for automatically installing the appropriate version of Fabric or Quilt is planned.

### Additional context

https://github.com/Gaming32/Superpack

**Comment by triphora** [comment]
Please feel free to submit a PR to add it yourself!

**Comment by MIfoodie** [comment]
> Please feel free to submit a PR to add it yourself!

I would like to be assigned this issue (if you have permissions to do that).

**Comment by triphora** [comment]
Anyone is free to do it.
