### ISSUE TITLE
Modrinth maven recommends using an `exclusiveContent` repository; this currently is not supported by forgegradle

### ISSUE THREAD

**Issue by lukebemish** [modrinth/docs#113]
### Describe the bug

The page on the modrinth maven (https://docs.modrinth.com/docs/tutorials/maven/) currently recommends using gradle's `exclusiveContent` filter for adding the repository; it should be noted on that page that this does not work with forgegradle (MinecraftForge/ForgeGradle#925).

**Comment by lukebemish** [comment]
To add more information: this is apparently possible with forgegradle but requires a bit of other stuff to be added to the block

**Comment by triphora** [comment]
What other stuff needs to be added?

**Comment by lukebemish** [comment]
According to someone on the linked issue, you need to add `fg.repository` to the exclusive repositories block. So:
```gradle
repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        forRepositories(fg.repository) // this is the new bit
        filter {
            includeGroup "maven.modrinth"
        }
    }
}
```
I haven't actually tested this though
