### ISSUE TITLE
Move BakaXL to the end of the "Playing modpacks" page

### ISSUE THREAD

**Issue by HyperSoop** [modrinth/docs#114]
### Is your suggested enhancement related to a problem? Please describe.

BakaXL is a launcher targeting Chinese communities and isn't what most Modrinth users would use, so it doesn't make sence that it's above MultiMC and Prism Launcher on the Playing Modpacks documentation page and therefore is made look like the more desirable option.

### Describe the solution you'd like

Move BakaXL to the end of the page.

**Comment by triphora** [comment]
Implemented in 291dec555ebc4bcb449d567d506f74216e2caaf8
