### ISSUE TITLE
Adding mention of "mc-modpack-kit" in docs

### ISSUE THREAD

**Issue by jh-devv** [modrinth/docs#122]
### Is your suggested enhancement related to a problem? Please describe.

Hey!
I'm the maintainer of [mc-modpack-kit](https://github.com/jh-devv/mc-modpack-kit) which basically provides a template for creating modpacks, updating them and uploading them to e.g. Modrinth

### Describe the solution you'd like

I would like to add a mention of my project in the "Creating Modpacks" docs.
Would this be possible?

### Additional context

The project is still in its early stages though!

**Comment by triphora** [comment]
Please submit a PR.

**Comment by jh-devv** [comment]
@triphora I made it a pr #124

**Comment by triphora** [comment]
Closed in #124
