### ISSUE TITLE
Move technical pages back from the support site

### ISSUE THREAD

**Issue by evur** [modrinth/docs#148]
Hi,
just a few days ago, I searched for documentation on the mrpack format and found [this page](https://web.archive.org/web/20240105180216/https://docs.modrinth.com/modpacks/format) in the docs. Yesterday, I noticed that the page got moved to the support site ([link](https://support.modrinth.com/en/articles/8802351-modrinth-modpack-format-mrpack)).

The support site is good. But I think that the documentation is better suited for technical pages. This gives the advantages of having them all in one place and being able to read them better due to features like syntax highlighting and navigation.

So my proposal is to move the following pages back to the documentation:
- Contributing to Modrinth
- Modpack Format
- Modrinth Maven Usage

**Comment by triphora** [comment]
Ultimately the goal is to use the support site for everything and make the API spec standalone, getting rid of the docs entirely (mostly anyway). So for most intents and purposes (besides the API spec) you should be using the support site first.

**Comment by evur** [comment]
The problem is that the support site is unsuited for documentation purposes. It misses syntax highlighting, the navigation left and right, links to headers and is also too narrow. I don't think that's going to change as its made for a different purpose overall.

**Comment by triphora** [comment]
While I understand that there are certain disadvantages to moving, we believe it to make more sense for our purposes to move as much information as much as possible to the new site. The new support site is tied to a broader push to consolidate our support and community engagement efforts to make it simpler both for users and for us as the team giving support.
