### ISSUE TITLE
Non existent projects return an empty page instead of an error

### ISSUE THREAD

**Issue by Pbone3** [modrinth/docs#37]
**Describe the bug**
The Modrinth API spec says that trying to fetch a project with a non existent id or slug (say, `api.modrinth.com/v2/project/thisisafakeslug`) should return a JSON response such as the following:
```
{
  "error": "not_found",
  "description": "the requested route does not exist"
}
```
But it actually returns nothing.

**To Reproduce**
1. Go to https://api.modrinth.com/v2/project/thisisafakeslug
2. See that no JSON is returned :(

**Expected behavior**
The JSON specified in the api spec would be returned.

**Additional context**
N/A

**Comment by wafflecoffee** [comment]
Resolved in 19c0290c
