### ISSUE TITLE
Document how to set up Authentication locally

### ISSUE THREAD

**Issue by ModProg** [modrinth/docs#49]
Maybe there also needs to be some things done to make it easier, and I have not yet figured out how to actually get my local website "authenticated" when connected to a local backend.

1. Create a `OAuth App` at https://github.com/settings/apps
2. Homepage does not matter, callback =`http://localhost:8000/v2/auth/callback`
3. Set `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` according to the application you just created.
4. Start the backend `cargo run`
5. Open http://localhost:8000/v2/auth/init?url=http://localhost:1234 (the port at the end does not matter as long as it is not currently serving a website)
6. You get the authentication token in the Address bar `?code=gho_oA.....` and can use that for local requests now.

**Comment by ExoPlant** [comment]
> Maybe there also needs to be some things done to make it easier, and I have not yet figured out how to actually get my local website "authenticated" when connected to a local backend.
> 
>     1. Create a `OAuth App` at https://github.com/settings/apps
> 
>     2. Homepage does not matter, callback =`http://localhost:8000/v2/auth/callback`
> 
>     3. Set `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` according to the application you just created.
> 
>     4. Start the backend `cargo run`
> 
>     5. Open http://localhost:8000/v2/auth/init?url=http://localhost:1234 (the port at the end does not matter as long as it is not currently serving a website)
> 
>     6. You get the authentication token in the Address bar `?code=gho_oA.....` and can use that for local requests now.

Have you set the correct api redirect url on the github application? That was the issue for me

**Comment by ModProg** [comment]
> Have you set the correct api redirect url on the github application? That was the issue for me

I set it to `http://localhost:8000/v2/auth/callback` like I wrote above.

Does the local frontend connect to your local backend? Does it show yourself as logged in?

**Comment by ExoPlant** [comment]
> > Have you set the correct api redirect url on the github application? That was the issue for me
> 
> I set it to `http://localhost:8000/v2/auth/callback` like I wrote above.
> 
> Does the local frontend connect to your local backend? Does it show yourself as logged in?

Yeah, it works for me
