### ISSUE TITLE
Create a version: The `dependencies` property is not marked as required

### ISSUE THREAD

**Issue by MMK21Hub** [modrinth/docs#76]
### The bug
In [the API documentation for the "Create a version" route](https://docs.modrinth.com/api-spec/#tag/versions/operation/createVersion) (`POST /version`), the `dependencies` field in the request body is not listed as required. However, the API treats it as a required field. (See [the relevant labrinth source code](https://github.com/modrinth/labrinth/blob/9fed1cde258d677420173caf13715cccc3758261/src/routes/version_creation.rs#L57), where you can compare the `dependencies` field to the actually-optional `version_body` field.)

In addition, the documentation mentions that the `dependencies` field can be set to null, but this is also contrary to how the API behaves.

#### API error message
```
Error while parsing JSON: missing field `dependencies` at line 1 column 240
```

### To Reproduce
Verify that [the documentation](https://docs.modrinth.com/api-spec/#tag/versions/operation/createVersion) doesn't mark the `dependencies` property as required.

Sending a HTTP POST request to https://staging-api.modrinth.com/v2/version with an otherwise-valid payload that doesn't include the `dependencies` field. Verify that the API responds with an error.

### Expected behavior
The documentation would mark the `dependencies` property as required, and it would not mention the possibility of it being `null`.

The documentation should also note that to create a version without dependencies, an empty array should be provided. Note that this is what the official frontend does when creating a version.

### Notes
Geometrically has confirmed that the current API behaviour is indeed correct [in a comment](https://github.com/modrinth/docs/issues/76#issuecomment-1312601918).

**Comment by triphora** [comment]
I don't see why we can't just do default Vec::new on it

**Comment by misode** [comment]
This is still an issue. It doesn't matter whether it's optional or whether you have to specify an empty list, but the docs should be fixed to reflect the current state.

**Comment by MMK21Hub** [comment]
I've updated the issue's description to reflect it being moved to the `docs` project.
