### ISSUE TITLE
Sidebar Menu Cut Off at Top

### ISSUE THREAD

**Issue by catter1** [modrinth/docs#80]
### Describe the bug

When looking at the API docs, the sidebar menu will get cut off at the top after reloading the page *and* opening a dropdown menu on the side. I'm assuming this has to do with the sidebar having a scrollbar/overflow and the website not correctly shifting the start of the sidebar down.

The first image is how it looks when going to the [docs](https://docs.modrinth.com/api-spec) directly for the first time, and the second image is after reloading and opening one of the dropdown menus (or entering a [link with a section](https://docs.modrinth.com/api-spec/#tag/projects)) in either order.

![image](https://user-images.githubusercontent.com/63272345/210152244-742a3314-56a8-4523-a79d-a4944e0d6ec6.png)

![image](https://user-images.githubusercontent.com/63272345/210152271-642fbcee-30f8-49f2-9744-d15af824693c.png)

### Steps to reproduce

1. Go to https://docs.modrinth.com/api-spec/
2. Click on the "Projects" dropdown menu on the sidebar
3. Refresh the webpage (sometimes, even this is unnecessary)

### Expected behavior

The sidebar should not be covered up at the top.

### Additional context

I am running a Chromium-based browser on Ubuntu 22.04.1 LTS.

**Comment by triphora** [comment]
I'm afraid we have no control over this. Please report this to Redocly.
