### ISSUE TITLE
A page detailing how to find/ask permission for including projects in modpacks

### ISSUE THREAD

**Issue by Minenash** [modrinth/docs#82]
### Is your feature request related to a problem? Please describe.

It's not uncommon for modpack authors to not know which projects they are allowed to include in their modpacks

### Describe the solution you'd like

A page that lists common ways to know, including:
- A list of common licenses that allow it automatically
- Phrases to look out for on project pages
- If in doubt contact the author

### Describe alternatives you've considered

The status quo

### Additional context

(totally not weeks late)

**Comment by MIfoodie** [comment]
I personally don’t think that this is needed. People should use their best judgement when making mod packs. If someone does not respect the IP of the owner of one of the included mod(s), it can be reported using the reporting feature in Modrinth.

**Comment by Minenash** [comment]
The moderation team already checks to see if they follow the projects' licenses. It's not 100% full proof and they are still responsible for making sure they don't violate copyright law.

And iirc most packs are rejected the first time around for violating copyright law. I don't think it's wise for modrinth to stop checking knowing full well that the majority are violating the law.

That being said, your comment doesn't seem to be actually connected with the post? Even if modrinth didn't check, it's still I good idea to include documentation on how to make a pack without violating the law. It's also (at least when I created the issue) a very common question asked on the discord server. They already have to read the docs on how to make a pack, so they are more likely to have their question answered without having to ask

**Comment by MIfoodie** [comment]
Alright. I might write something up tomorrow about this and put a PR in.

**Comment by triphora** [comment]
Fixed in e97b7a7
